version: 3
networks: 
    hasibproject_network:

services:
    db:
        container_name: hasibprojectdb
        image: mysql:8
        volume: 
            - ./database:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
        network:
            - hasibproject_network

    phpmyadmin: 
        container_name: hasibproject_phpmyadmin
        depends_on: 
            -db
        image: phpmyadmin
        restart: always
        ports: 
            - 8080:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        network: 
            - hasibproject_network


    web:
        image: php:7.2.2-apache
        container_name: hasibproject_php
        depends_on:
            - db
        restart: always
        volumes:
            - ./php/:/var/www/html/
        ports:
            - "80:80"
        stdin_open: true
        tty: true 